### PR TITLE
When yum.conf specifies a proxy, use that proxy to fetch the erratas

### PR DESCRIPTION
**Pull request by stephane-martin**
fixes: #16 

I did some basic tests with a few proxies, but it should probably be tested more thoroughly before being merged.

It was somewhat painful to avoid any new dependency (such as requests), so there is a few lines of urllib2 stuff to open the Errata URL through a proxy.

Finally, it should be noted that Python supports opening HTTPS ressources through a proxy only since 2.6.2.

### CODE REVIEW

**Comment by wied03** [comment]
I'll need to see why the test is failing first.

**Comment by stephane-martin** [comment]
Something related to ipython (???) install on Redhat, where it lacks gcc to compile the native modules. I don't really see how that could be related to the PR...

**Comment by wied03** [comment]
Yeah it probably isn't. I'll try and address it in master and then merge in the PR.

**Comment by wied03** [comment]
You're right, same problem on master build - https://travis-ci.org/wied03/centos-package-cron/jobs/149351998. Something environment/version wise since the master code hasn't changed in a while.

**Comment by wied03** [comment]
@stephane-martin - Fixed the master build by removing the ipython dependency that I don't really need anyways. Can you rebase your branch against master and push so that I can confirm travis passes?

**Pull request merged**
