### PR TITLE
Fixes #3 UnicodeEncodeError: 'ascii' codec can't encode characters

### PR DESCRIPTION
**Pull request by paulmaunders**
These changes should allow output redirection of the script.

### CODE REVIEW

**Comment by wied03** [comment]
I'll try and add some tests for this and then merge it.

**Comment by wied03** [comment]
Thanks for the PR.

**Comment by wied03** [comment]
Merged in via 3ac5b7b76d4c323c70d2148653dddf2c52fff42e in the develop branch

**Comment by wied03** [comment]
@paulmaunders - I couldn't replicate this with the tests that are now in master but I put the fix in anyways. Did you have another language on your system?

**Comment by paulmaunders** [comment]
I was using...
CentOS Linux release 7.2.1511 (Core) 
Python 2.7.5

**Pull request closed without merging**
